### ISSUE TITLE
Web-server not Open

### ISSUE THREAD

**Issue by miniluphy** [kcri-tz/plasmidfinder#1]
Sorry to bother you. It seems to be closed when I clicked the web-server website （https://cge.cbs.dtu.dk/services/PlasmidFinder/）. Is there anything wrong? Thank you.

**Comment by zwets** [comment]
I would suggest accessing the CGE services via: [https://www.genomicepidemiology.org/services](https://www.genomicepidemiology.org/services). It looks like PlasmidFinder may be down. There is a "Contact" link on that page to contact the CGE help desk.
